export type Tematica = 'Ambiental' | 'Tecnológica' | 'Política' | 'Social' | 'Económica' | 'General';
export type CategoriaProspectiva = 'Señal Débil' | 'Carta Salvaje' | 'Tecnología Emergente' | 'Ruptura o disrupción' | 'Evento catastrófico';
export type Categoria = '' | 'Carta Salvaje' | 'Tecnología Emergente' | 'Ruptura o disrupción' | 'Evento catastrófico';
export type TipoEvento = '' | 'SD' | 'RD' | 'CS' | 'EC';

export const SVG_PATHS: Record<string, string> = {
  // Path para SD y RD
  SD_RD: 'M12.001 3C16.2854 3 20.2201 4.49683 23.3108 6.99607L22.4994 8H18.001L18.0004 13.571L12.001 21L0.69043 6.99671C3.78127 4.49709 7.71632 3 12.001 3ZM22.001 19V21H20.001V19H22.001ZM22.001 10V17H20.001V10H22.001Z',
  // Path para CS y EC
  CS_EC: 'M20,0H4C3.4,0,3,0.4,3,1v22c0,0.6,0.4,1,1,1h16c0.6,0,1-0.4,1-1V1C21,0.4,20.6,0,20,0z M19,22H5V2h14V22z M11,15v2h2v-2c2,0,3-1.1,3-3c0-2.2-2-3-4-6c-2,3-4,3.8-4,6C8,13.9,9,15,11,15z',
  // Path para Tecnologías Emergentes (TE)
  TE: 'M6 18H18V6H6V18ZM14 20H10V22H8V20H5C4.44772 20 4 19.5523 4 19V16H2V14H4V10H2V8H4V5C4 4.44772 4.44772 4 5 4H8V2H10V4H14V2H16V4H19C19.5523 4 20 4.44772 20 5V8H22V10H20V14H22V16H20V19C20 19.5523 19.5523 20 19 20H16V22H14V20ZM8 8H16V16H8V8Z'
};

export interface Evento {
  scg?: 'SD/RD' | 'CS/EC',
  nombre: string;
  tematica: Tematica;
  fechaActualizacion: string; // Ej. '30 sept 2024'
  urlFicha: string;
  categoria: CategoriaProspectiva;
  ejeEstrategico?: string;
  horizonte?: string;
  tipoEvento?: 'SD' | 'RD' | 'CS' | 'EC';
  categoriaPertenencia?: 'SD/RD' | 'CS/EC';
}

export const TEMATICA_SEVERITY: Record<Tematica, 'success' | 'info' | 'warning' | 'danger' | 'contrast' | 'secondary'> = {
  Ambiental: 'success',   // verde
  Tecnológica: 'info',    // azul
  Política: 'contrast',   // morado
  Social: 'danger',       // rojo
  Económica: 'warning',   // ámbar
  General: 'secondary'    // gris
};

export const DATABASE: Evento[] = [
  // --- SEÑALES DÉBILES (SD) / RUPTURAS O DISRUPCIONES (RD) ---
  { nombre: 'SD-Expansión de la ansiedad climática', tematica: 'Ambiental', fechaActualizacion: '30 sept 2024', urlFicha: 'https://observatorio.ceplan.gob.pe/ficha/S28', categoria: 'Señal Débil', ejeEstrategico: 'Territorio sostenible', horizonte: 'PRESENTE-2030', tipoEvento: 'SD', categoriaPertenencia: 'SD/RD' },
  { nombre: 'SD-Mayor uso de vehículos aéreos no tripulados', tematica: 'Tecnológica', fechaActualizacion: '20 dec 2024', urlFicha: 'https://observatorio.ceplan.gob.pe/ficha/S33', categoria: 'Señal Débil', ejeEstrategico: 'Competitividad e innovación', horizonte: '2040-2050', tipoEvento: 'SD', categoriaPertenencia: 'SD/RD' },
  { nombre: 'SD-Uso de la justicia a favor de la acción climática', tematica: 'Ambiental', fechaActualizacion: '20 dec 2024', urlFicha: 'https://observatorio.ceplan.gob.pe/ficha/S34', categoria: 'Señal Débil', ejeEstrategico: 'Territorio sostenible', horizonte: 'PRESENTE-2030', tipoEvento: 'SD', categoriaPertenencia: 'SD/RD' },
  { nombre: 'SD-Impresión 3D aplicada a la industria de la construcción', tematica: 'Tecnológica', fechaActualizacion: '28 nov 2025', urlFicha: 'https://observatorio.ceplan.gob.pe/ficha/S39', categoria: 'Señal Débil', ejeEstrategico: 'Competitividad e innovación', horizonte: '2030-2040', tipoEvento: 'SD', categoriaPertenencia: 'SD/RD' },
  { nombre: 'RD-Prolongada recesión económica', tematica: 'Económica', fechaActualizacion: '22 dec 2025', urlFicha: 'https://observatorio.ceplan.gob.pe/ficha/S41', categoria: 'Ruptura o disrupción', ejeEstrategico: 'Desarrollo de las personas', horizonte: '2030-2040', tipoEvento: 'RD', categoriaPertenencia: 'SD/RD' },
  { nombre: 'SD-Prolongada interrupción en la cadena de semiconductores', tematica: 'Tecnológica', fechaActualizacion: '20 dec 2024', urlFicha: 'https://observatorio.ceplan.gob.pe/ficha/S44', categoria: 'Señal Débil', ejeEstrategico: 'Competitividad e innovación', horizonte: '2030-2040', tipoEvento: 'SD', categoriaPertenencia: 'SD/RD' },
  { nombre: 'SD-Normalización de la cirugía robótica', tematica: 'Tecnológica', fechaActualizacion: '27 nov 2025', urlFicha: 'https://observatorio.ceplan.gob.pe/ficha/S38', categoria: 'Señal Débil', ejeEstrategico: 'Competitividad e innovación', horizonte: '2040-2050', tipoEvento: 'SD', categoriaPertenencia: 'SD/RD' },
  { nombre: 'SD-Surgimiento de la IA explicable', tematica: 'Tecnológica', fechaActualizacion: '31 jul 2024', urlFicha: 'https://observatorio.ceplan.gob.pe/ficha/s45', categoria: 'Señal Débil', ejeEstrategico: 'Competitividad e innovación', horizonte: '2040-2050', tipoEvento: 'SD', categoriaPertenencia: 'SD/RD' },
  { nombre: 'SD-Colonias urbanas flotantes por cambio climático', tematica: 'Ambiental', fechaActualizacion: '17 jul 2025', urlFicha: 'https://observatorio.ceplan.gob.pe/ficha/s50', categoria: 'Señal Débil', ejeEstrategico: 'Territorio sostenible', horizonte: '2040-2050', tipoEvento: 'SD', categoriaPertenencia: 'SD/RD' },
  { nombre: 'SD-Proliferación de incendios forestales en la Amazonía', tematica: 'Ambiental', fechaActualizacion: '17 jul 2025', urlFicha: 'https://observatorio.ceplan.gob.pe/ficha/s48', categoria: 'Señal Débil', ejeEstrategico: 'Territorio sostenible', horizonte: 'PRESENTE-2030', tipoEvento: 'SD', categoriaPertenencia: 'SD/RD' },
  { nombre: 'SD-Erosión de la soberanía por Big Tech', tematica: 'Económica', fechaActualizacion: '17 jul 2025', urlFicha: 'https://observatorio.ceplan.gob.pe/ficha/s49', categoria: 'Señal Débil', ejeEstrategico: 'Desarrollo de las personas', horizonte: '2030-2040', tipoEvento: 'SD', categoriaPertenencia: 'SD/RD' },
  { nombre: 'RD-Fin de la Internet abierta', tematica: 'Social', fechaActualizacion: '1 sept 2025', urlFicha: 'https://observatorio.ceplan.gob.pe/ficha/rd1', categoria: 'Ruptura o disrupción', ejeEstrategico: 'Democracia y paz', horizonte: '2030-2040', tipoEvento: 'RD', categoriaPertenencia: 'SD/RD' },
  { nombre: 'RD-Surgimiento de zonas inhabitables por temperaturas extremas', tematica: 'Ambiental', fechaActualizacion: '1 sept 2025', urlFicha: 'https://observatorio.ceplan.gob.pe/ficha/RD2', categoria: 'Ruptura o disrupción', ejeEstrategico: 'Territorio sostenible', horizonte: '2040-2050', tipoEvento: 'RD', categoriaPertenencia: 'SD/RD' },
  { nombre: 'SD-Descargas masivas de sulfuro de hidrógeno de océanos desoxigenados', tematica: 'Ambiental', fechaActualizacion: '2 sept 2025', urlFicha: 'https://observatorio.ceplan.gob.pe/ficha/S51', categoria: 'Señal Débil', ejeEstrategico: 'Territorio sostenible', horizonte: '2040-2050', tipoEvento: 'SD', categoriaPertenencia: 'SD/RD' },
  { nombre: 'RD-Normalización de la computación cuántica', tematica: 'Tecnológica', fechaActualizacion: '21 oct 2025', urlFicha: 'https://observatorio.ceplan.gob.pe/ficha/RD3', categoria: 'Ruptura o disrupción', ejeEstrategico: 'Competitividad e innovación', horizonte: 'PRESENTE-2030', tipoEvento: 'RD', categoriaPertenencia: 'SD/RD' },
  { nombre: 'RD-Surgimiento de la Inteligencia Artificial General', tematica: 'Tecnológica', fechaActualizacion: '21 oct 2025', urlFicha: 'https://observatorio.ceplan.gob.pe/ficha/RD6', categoria: 'Ruptura o disrupción', ejeEstrategico: 'Competitividad e innovación', horizonte: 'PRESENTE-2030', tipoEvento: 'RD', categoriaPertenencia: 'SD/RD' },
  { nombre: 'RD-Ruptura de ciberseguridad por capacidades cuánticas', tematica: 'Tecnológica', fechaActualizacion: '21 oct 2025', urlFicha: 'https://observatorio.ceplan.gob.pe/ficha/RD7', categoria: 'Ruptura o disrupción', ejeEstrategico: 'Competitividad e innovación', horizonte: 'PRESENTE-2030', tipoEvento: 'RD', categoriaPertenencia: 'SD/RD' },
  { nombre: 'SD-Normalización de la tecnología espacial', tematica: 'Tecnológica', fechaActualizacion: '21 oct 2025', urlFicha: 'https://observatorio.ceplan.gob.pe/ficha/SD52', categoria: 'Señal Débil', ejeEstrategico: 'Competitividad e innovación', horizonte: '2040-2050', tipoEvento: 'SD', categoriaPertenencia: 'SD/RD' },
  { nombre: 'RD-Longevidad extrema con biotecnología avanzada', tematica: 'Tecnológica', fechaActualizacion: '22 oct 2025', urlFicha: 'https://observatorio.ceplan.gob.pe/ficha/RD8', categoria: 'Ruptura o disrupción', ejeEstrategico: 'Competitividad e innovación', horizonte: '2030-2040', tipoEvento: 'RD', categoriaPertenencia: 'SD/RD' },
  { nombre: 'RD-Plena digitalización del mundo real en entornos virtuales', tematica: 'Tecnológica', fechaActualizacion: '22 oct 2025', urlFicha: 'https://observatorio.ceplan.gob.pe/ficha/RD9', categoria: 'Ruptura o disrupción', ejeEstrategico: 'Competitividad e innovación', horizonte: '2030-2040', tipoEvento: 'RD', categoriaPertenencia: 'SD/RD' },
  { nombre: 'SD-Propagación de modelos de IA ultraeficientes y portátiles', tematica: 'Tecnológica', fechaActualizacion: '22 oct 2025', urlFicha: 'https://observatorio.ceplan.gob.pe/ficha/SD53', categoria: 'Señal Débil', ejeEstrategico: 'Competitividad e innovación', horizonte: '2030-2040', tipoEvento: 'SD', categoriaPertenencia: 'SD/RD' },
  { nombre: 'SD-Escalada de la Muskonomía', tematica: 'Tecnológica', fechaActualizacion: '22 oct 2025', urlFicha: 'https://observatorio.ceplan.gob.pe/ficha/SD54', categoria: 'Señal Débil', ejeEstrategico: 'Competitividad e innovación', horizonte: '2030-2040', tipoEvento: 'SD', categoriaPertenencia: 'SD/RD' },
  { nombre: 'SD-Restauración natural de ecosistemas degradados por proyectos bioeconómicos', tematica: 'Ambiental', fechaActualizacion: '31 oct 2025', urlFicha: 'https://observatorio.ceplan.gob.pe/ficha/SD55', categoria: 'Señal Débil', ejeEstrategico: 'Territorio sostenible', horizonte: '2040-2050', tipoEvento: 'SD', categoriaPertenencia: 'SD/RD' },
  { nombre: 'SD-Normalización de ciudades submarinas o subterráneas', tematica: 'Social', fechaActualizacion: '31 oct 2025', urlFicha: 'https://observatorio.ceplan.gob.pe/ficha/RD10', categoria: 'Señal Débil', ejeEstrategico: 'Democracia y paz', horizonte: '2040-2050', tipoEvento: 'SD', categoriaPertenencia: 'SD/RD' },
  { nombre: 'RD-Captura criminal del Estado y pérdida del control territorial en el Perú', tematica: 'Social', fechaActualizacion: '31 oct 2025', urlFicha: 'https://observatorio.ceplan.gob.pe/ficha/RD11', categoria: 'Ruptura o disrupción', ejeEstrategico: 'Democracia y paz', horizonte: 'PRESENTE-2030', tipoEvento: 'RD', categoriaPertenencia: 'SD/RD' },
  { nombre: 'SD-Avances en geoingeniería regional', tematica: 'Ambiental', fechaActualizacion: '3 nov 2025', urlFicha: 'https://observatorio.ceplan.gob.pe/ficha/SD56', categoria: 'Señal Débil', ejeEstrategico: 'Territorio sostenible', horizonte: 'PRESENTE-2030', tipoEvento: 'SD', categoriaPertenencia: 'SD/RD' },
  { nombre: 'RD-Política del más fuerte vuelve a imperar en el mundo', tematica: 'Política', fechaActualizacion: '3 nov 2025', urlFicha: 'https://observatorio.ceplan.gob.pe/ficha/rd12', categoria: 'Ruptura o disrupción', ejeEstrategico: 'Democracia y paz', horizonte: 'PRESENTE-2030', tipoEvento: 'RD', categoriaPertenencia: 'SD/RD' },
  { nombre: 'RD-Fragilidad del Estado de derecho en el Perú', tematica: 'Política', fechaActualizacion: '3 nov 2025', urlFicha: 'https://observatorio.ceplan.gob.pe/ficha/rd13', categoria: 'Ruptura o disrupción', ejeEstrategico: 'Democracia y paz', horizonte: 'PRESENTE-2030', tipoEvento: 'RD', categoriaPertenencia: 'SD/RD' },
  { nombre: 'RD-Fin de la democracia y retorno al autoritarismo', tematica: 'Política', fechaActualizacion: '3 nov 2025', urlFicha: 'https://observatorio.ceplan.gob.pe/ficha/rd14', categoria: 'Ruptura o disrupción', ejeEstrategico: 'Democracia y paz', horizonte: 'PRESENTE-2030', tipoEvento: 'RD', categoriaPertenencia: 'SD/RD' },
  { nombre: 'SD-Desarrollo de políticas e instituciones inclusivas', tematica: 'Política', fechaActualizacion: '3 nov 2025', urlFicha: 'https://observatorio.ceplan.gob.pe/ficha/sd57', categoria: 'Señal Débil', ejeEstrategico: 'Democracia y paz', horizonte: '2040-2050', tipoEvento: 'SD', categoriaPertenencia: 'SD/RD' },
  { nombre: 'SD-Uso generalizado de implantes neuronales', tematica: 'Tecnológica', fechaActualizacion: '22 dec 2025', urlFicha: 'https://observatorio.ceplan.gob.pe/ficha/sd49', categoria: 'Señal Débil', ejeEstrategico: 'Competitividad e innovación', horizonte: '2040-2050', tipoEvento: 'SD', categoriaPertenencia: 'SD/RD' },
  { nombre: 'SD-Despegue de la minería espacial', tematica: 'Tecnológica', fechaActualizacion: '31 dec 2025', urlFicha: 'https://observatorio.ceplan.gob.pe/ficha/sd58', categoria: 'Señal Débil', ejeEstrategico: 'Competitividad e innovación', horizonte: '2040-2050', tipoEvento: 'SD', categoriaPertenencia: 'SD/RD' },

  // --- CARTAS SALVAJES (CS) / EVENTOS CATASTRÓFICOS (EC) ---
  { nombre: 'EC-Extraordinario Fenómeno de El Niño', tematica: 'Ambiental', fechaActualizacion: '6 jul 2026', urlFicha: 'https://observatorio.ceplan.gob.pe/ficha/S24', categoria: 'Evento catastrófico', ejeEstrategico: 'Territorio sostenible', horizonte: 'PRESENTE-2030', tipoEvento: 'EC', categoriaPertenencia: 'CS/EC' },
  { nombre: 'EC-Amenaza de bioterrorismo con patógenos modificados', tematica: 'Social', fechaActualizacion: '16 jul 2025', urlFicha: 'https://observatorio.ceplan.gob.pe/ficha/C6', categoria: 'Evento catastrófico', ejeEstrategico: 'Democracia y paz', horizonte: '2030-2040', tipoEvento: 'EC', categoriaPertenencia: 'CS/EC' },
  { nombre: 'CS-Ataque a satélites', tematica: 'Tecnológica', fechaActualizacion: '20 dec 2024', urlFicha: 'https://observatorio.ceplan.gob.pe/ficha/C9', categoria: 'Carta Salvaje', ejeEstrategico: 'Competitividad e innovación', horizonte: '2030-2040', tipoEvento: 'CS', categoriaPertenencia: 'CS/EC' },
  { nombre: 'CS-Liberación de patógenos por deshielo de glaciares', tematica: 'Ambiental', fechaActualizacion: '14 jul 2025', urlFicha: 'https://observatorio.ceplan.gob.pe/ficha/C10', categoria: 'Carta Salvaje', ejeEstrategico: 'Territorio sostenible', horizonte: '2030-2040', tipoEvento: 'CS', categoriaPertenencia: 'CS/EC' },
  { nombre: 'CS-Erupción volcánica de gran magnitud', tematica: 'Ambiental', fechaActualizacion: '20 dec 2024', urlFicha: 'https://observatorio.ceplan.gob.pe/ficha/C12', categoria: 'Carta Salvaje', ejeEstrategico: 'Territorio sostenible', horizonte: 'PRESENTE-2030', tipoEvento: 'CS', categoriaPertenencia: 'CS/EC' },
  { nombre: 'CS-Aprovechamiento ético y sostenible de la biología sintética', tematica: 'Tecnológica', fechaActualizacion: '20 may 2025', urlFicha: 'https://observatorio.ceplan.gob.pe/ficha/C15', categoria: 'Carta Salvaje', ejeEstrategico: 'Competitividad e innovación', horizonte: '2030-2040', tipoEvento: 'CS', categoriaPertenencia: 'CS/EC' },
  { nombre: 'CS-Guerra civil por convulsión social', tematica: 'Política', fechaActualizacion: '20 dec 2024', urlFicha: 'https://observatorio.ceplan.gob.pe/ficha/C18', categoria: 'Carta Salvaje', ejeEstrategico: 'Democracia y paz', horizonte: 'PRESENTE-2030', tipoEvento: 'CS', categoriaPertenencia: 'CS/EC' },
  { nombre: 'CS-Edición del genoma humano para tratamientos médicos', tematica: 'Tecnológica', fechaActualizacion: '20 dec 2024', urlFicha: 'https://observatorio.ceplan.gob.pe/ficha/C19', categoria: 'Carta Salvaje', ejeEstrategico: 'Competitividad e innovación', horizonte: '2040-2050', tipoEvento: 'CS', categoriaPertenencia: 'CS/EC' },
  { nombre: 'CS-Mayor implementación de la manufactura aditiva 4D', tematica: 'Tecnológica', fechaActualizacion: '20 dec 2024', urlFicha: 'https://observatorio.ceplan.gob.pe/ficha/C20', categoria: 'Carta Salvaje', ejeEstrategico: 'Competitividad e innovación', horizonte: '2040-2050', tipoEvento: 'CS', categoriaPertenencia: 'CS/EC' },
  { nombre: 'CS-Extinción de la Unión Europea', tematica: 'Política', fechaActualizacion: '20 dec 2024', urlFicha: 'https://observatorio.ceplan.gob.pe/ficha/C21', categoria: 'Carta Salvaje', ejeEstrategico: 'Democracia y paz', horizonte: '2030-2040', tipoEvento: 'CS', categoriaPertenencia: 'CS/EC' },
  { nombre: 'CS-Transformación del sistema de salud hacia hospitales virtuales', tematica: 'Tecnológica', fechaActualizacion: '28 oct 2024', urlFicha: 'https://observatorio.ceplan.gob.pe/ficha/C23', categoria: 'Carta Salvaje', ejeEstrategico: 'Competitividad e innovación', horizonte: '2040-2050', tipoEvento: 'CS', categoriaPertenencia: 'CS/EC' },
  { nombre: 'CS-Escalada de una guerra nuclear', tematica: 'General', fechaActualizacion: '20 may 2025', urlFicha: 'https://observatorio.ceplan.gob.pe/ficha/C24', categoria: 'Carta Salvaje', ejeEstrategico: 'Democracia y paz', horizonte: '2030-2040', tipoEvento: 'CS', categoriaPertenencia: 'CS/EC' },
  { nombre: 'CS-Colapso económico en los Estados Unidos', tematica: 'Económica', fechaActualizacion: '20 dec 2024', urlFicha: 'https://observatorio.ceplan.gob.pe/ficha/c25', categoria: 'Carta Salvaje', ejeEstrategico: 'Desarrollo de las personas', horizonte: '2030-2040', tipoEvento: 'CS', categoriaPertenencia: 'CS/EC' },
  { nombre: 'CS-Fracaso en la adopción de la IA', tematica: 'Tecnológica', fechaActualizacion: '20 dec 2024', urlFicha: 'https://observatorio.ceplan.gob.pe/ficha/c26', categoria: 'Carta Salvaje', ejeEstrategico: 'Competitividad e innovación', horizonte: '2030-2040', tipoEvento: 'CS', categoriaPertenencia: 'CS/EC' },
  { nombre: 'CS-Gran tormenta solar', tematica: 'Ambiental', fechaActualizacion: '7 feb 2025', urlFicha: 'https://observatorio.ceplan.gob.pe/ficha/C27', categoria: 'Carta Salvaje', ejeEstrategico: 'Territorio sostenible', horizonte: '2040-2050', tipoEvento: 'CS', categoriaPertenencia: 'CS/EC' },
  { nombre: 'CS-Colapso del sistema energético global', tematica: 'Social', fechaActualizacion: '17 jul 2025', urlFicha: 'https://observatorio.ceplan.gob.pe/ficha/c28', categoria: 'Carta Salvaje', ejeEstrategico: 'Democracia y paz', horizonte: '2030-2040', tipoEvento: 'CS', categoriaPertenencia: 'CS/EC' },
  { nombre: 'CS-Universalización de la renta básica', tematica: 'Económica', fechaActualizacion: '17 jul 2025', urlFicha: 'https://observatorio.ceplan.gob.pe/ficha/S35', categoria: 'Carta Salvaje', ejeEstrategico: 'Desarrollo de las personas', horizonte: '2030-2040', tipoEvento: 'CS', categoriaPertenencia: 'CS/EC' },
  { nombre: 'CS-Transformación del Amazonas en sabana por pérdida de humedad', tematica: 'Ambiental', fechaActualizacion: '2 sept 2025', urlFicha: 'https://observatorio.ceplan.gob.pe/ficha/C30', categoria: 'Carta Salvaje', ejeEstrategico: 'Desarrollo de las personas', horizonte: '2030-2040', tipoEvento: 'CS', categoriaPertenencia: 'CS/EC' },
  { nombre: 'CS-Pérdida de control de la IA', tematica: 'Tecnológica', fechaActualizacion: '16 sept 2025', urlFicha: 'https://observatorio.ceplan.gob.pe/ficha/C31', categoria: 'Carta Salvaje', ejeEstrategico: 'Desarrollo de las personas', horizonte: 'PRESENTE-2030', tipoEvento: 'CS', categoriaPertenencia: 'CS/EC' },
  { nombre: 'CS-Fallo crítico en un acelerador de partículas', tematica: 'Tecnológica', fechaActualizacion: '21 oct 2025', urlFicha: 'https://observatorio.ceplan.gob.pe/ficha/CS6', categoria: 'Carta Salvaje', ejeEstrategico: 'Desarrollo de las personas', horizonte: '2030-2040', tipoEvento: 'CS', categoriaPertenencia: 'CS/EC' },
  { nombre: 'CS-Colapso de Internet', tematica: 'Tecnológica', fechaActualizacion: '3 nov 2025', urlFicha: 'https://observatorio.ceplan.gob.pe/ficha/S35', categoria: 'Carta Salvaje', ejeEstrategico: 'Desarrollo de las personas', horizonte: '2030-2040', tipoEvento: 'CS', categoriaPertenencia: 'CS/EC' },
  { nombre: 'EC-Incontrolables pandemias más graves', tematica: 'Social', fechaActualizacion: '1 sept 2025', urlFicha: 'https://observatorio.ceplan.gob.pe/ficha/EC1', categoria: 'Carta Salvaje', ejeEstrategico: 'Desarrollo de las personas', horizonte: '2030-2040', tipoEvento: 'EC', categoriaPertenencia: 'CS/EC' },
  { nombre: 'EC-Amenaza por supernovas y estallidos de rayos gamma', tematica: 'Ambiental', fechaActualizacion: '1 sept 2025', urlFicha: 'https://observatorio.ceplan.gob.pe/ficha/EC2', categoria: 'Carta Salvaje', ejeEstrategico: 'Desarrollo de las personas', horizonte: '2030-2040', tipoEvento: 'EC', categoriaPertenencia: 'CS/EC' },
  { nombre: 'EC-Colisión de asteroides y cometas', tematica: 'Ambiental', fechaActualizacion: '1 sept 2025', urlFicha: 'https://observatorio.ceplan.gob.pe/ficha/EC3', categoria: 'Carta Salvaje', ejeEstrategico: 'Desarrollo de las personas', horizonte: '2030-2040', tipoEvento: 'EC', categoriaPertenencia: 'CS/EC' },
  { nombre: 'EC-Descontrol por agentes biológicos sintéticos', tematica: 'Tecnológica', fechaActualizacion: '21 oct 2025', urlFicha: 'https://observatorio.ceplan.gob.pe/ficha/EC4', categoria: 'Carta Salvaje', ejeEstrategico: 'Desarrollo de las personas', horizonte: '2030-2040', tipoEvento: 'EC', categoriaPertenencia: 'CS/EC' },
  { nombre: 'EC-Colapso de biodiversidad andina por sobreexplotación', tematica: 'Ambiental', fechaActualizacion: '3 nov 2025', urlFicha: 'https://observatorio.ceplan.gob.pe/ficha/EC6', categoria: 'Carta Salvaje', ejeEstrategico: 'Desarrollo de las personas', horizonte: '2030-2040', tipoEvento: 'EC', categoriaPertenencia: 'CS/EC' },
  { nombre: 'EC-Ascenso del caos geopolítico global', tematica: 'Política', fechaActualizacion: '3 nov 2025', urlFicha: 'https://observatorio.ceplan.gob.pe/ficha/EC7', categoria: 'Carta Salvaje', ejeEstrategico: 'Desarrollo de las personas', horizonte: '2030-2040', tipoEvento: 'EC', categoriaPertenencia: 'CS/EC' },
  { nombre: 'EC-Tercera Guerra Mundial', tematica: 'Política', fechaActualizacion: '3 nov 2025', urlFicha: 'https://observatorio.ceplan.gob.pe/ficha/EC8', categoria: 'Carta Salvaje', ejeEstrategico: 'Desarrollo de las personas', horizonte: '2030-2040', tipoEvento: 'EC', categoriaPertenencia: 'CS/EC' },

  // --- Tecnología emergente ---
  { nombre: 'Aplicaciones inteligentes: el futuro de la tecnología móvil', tematica: 'Tecnológica', fechaActualizacion: '14 aug 2023', urlFicha: 'https://observatorio.ceplan.gob.pe/ficha/TE_01', categoria: 'Tecnología Emergente', ejeEstrategico: 'Desarrollo de las personas', horizonte: '2030-2040' },
  { nombre: '6G: la próxima generación de tecnología móvil', tematica: 'Tecnológica', fechaActualizacion: '14 aug 2023', urlFicha: 'https://observatorio.ceplan.gob.pe/ficha/TE_02', categoria: 'Tecnología Emergente', ejeEstrategico: 'Desarrollo de las personas', horizonte: '2030-2040' },
  { nombre: 'Blockchain: transformando industrias a través de la tecnología descentralizada', tematica: 'Tecnológica', fechaActualizacion: '14 aug 2023', urlFicha: 'https://observatorio.ceplan.gob.pe/ficha/TE_03', categoria: 'Tecnología Emergente', ejeEstrategico: 'Desarrollo de las personas', horizonte: '2030-2040' },
  { nombre: 'Computación espacial: La tecnología que está cambiando el mundo', tematica: 'Tecnológica', fechaActualizacion: '14 aug 2023', urlFicha: 'https://observatorio.ceplan.gob.pe/ficha/TE_04', categoria: 'Tecnología Emergente', ejeEstrategico: 'Desarrollo de las personas', horizonte: '2030-2040' },
  { nombre: 'Computer vision: la visión artificial', tematica: 'Tecnológica', fechaActualizacion: '14 aug 2023', urlFicha: 'https://observatorio.ceplan.gob.pe/ficha/TE_05', categoria: 'Tecnología Emergente', ejeEstrategico: 'Desarrollo de las personas', horizonte: '2030-2040' },
  { nombre: 'Datos sintéticos: la generación artificial de datos', tematica: 'Tecnológica', fechaActualizacion: '14 aug 2023', urlFicha: 'https://observatorio.ceplan.gob.pe/ficha/TE_06', categoria: 'Tecnología Emergente', ejeEstrategico: 'Desarrollo de las personas', horizonte: '2030-2040' },
  { nombre: 'Edge AI: Potenciando la Inteligencia Artificial', tematica: 'Tecnológica', fechaActualizacion: '14 aug 2023', urlFicha: 'https://observatorio.ceplan.gob.pe/ficha/TE_07', categoria: 'Tecnología Emergente', ejeEstrategico: 'Desarrollo de las personas', horizonte: '2030-2040' },
  { nombre: 'Espacio inteligente: la tecnología emergente que transforma los entornos inteligentes', tematica: 'Tecnológica', fechaActualizacion: '14 aug 2023', urlFicha: 'https://observatorio.ceplan.gob.pe/ficha/TE_08', categoria: 'Tecnología Emergente', ejeEstrategico: 'Desarrollo de las personas', horizonte: '2030-2040' },
  { nombre: 'Gemelos digitales: impulsando la conectividad y la optimización', tematica: 'Tecnológica', fechaActualizacion: '14 aug 2023', urlFicha: 'https://observatorio.ceplan.gob.pe/ficha/TE_09', categoria: 'Tecnología Emergente', ejeEstrategico: 'Desarrollo de las personas', horizonte: '2030-2040' },
  { nombre: 'Inteligencia Artificial generativa: impulsando la creatividad y la innovación', tematica: 'Tecnológica', fechaActualizacion: '14 aug 2023', urlFicha: 'https://observatorio.ceplan.gob.pe/ficha/TE_10', categoria: 'Tecnología Emergente', ejeEstrategico: 'Desarrollo de las personas', horizonte: '2030-2040' },
  { nombre: 'Human - Centered AI: la inteligencia artificial centrada en las personas', tematica: 'Tecnológica', fechaActualizacion: '14 aug 2023', urlFicha: 'https://observatorio.ceplan.gob.pe/ficha/TE_11', categoria: 'Tecnología Emergente', ejeEstrategico: 'Desarrollo de las personas', horizonte: '2030-2040' },
  { nombre: 'Hyperscale Edge Computing: impulsando el futuro de la computación distribuida', tematica: 'Tecnológica', fechaActualizacion: '14 aug 2023', urlFicha: 'https://observatorio.ceplan.gob.pe/ficha/TE_12', categoria: 'Tecnología Emergente', ejeEstrategico: 'Desarrollo de las personas', horizonte: '2030-2040' },
  { nombre: 'Identidad descentralizada: empoderando a los individuos con el control de su identidad digital', tematica: 'Tecnológica', fechaActualizacion: '14 aug 2023', urlFicha: 'https://observatorio.ceplan.gob.pe/ficha/TE_13', categoria: 'Tecnología Emergente', ejeEstrategico: 'Desarrollo de las personas', horizonte: '2030-2040' },
  { nombre: 'Grafos de conocimiento: el futuro de la integración de datos', tematica: 'Tecnológica', fechaActualizacion: '14 aug 2023', urlFicha: 'https://observatorio.ceplan.gob.pe/ficha/TE_14', categoria: 'Tecnología Emergente', ejeEstrategico: 'Desarrollo de las personas', horizonte: '2030-2040' },
  { nombre: 'Metaverso: redefiniendo la realidad virtual', tematica: 'Tecnológica', fechaActualizacion: '14 aug 2023', urlFicha: 'https://observatorio.ceplan.gob.pe/ficha/TE_15', categoria: 'Tecnología Emergente', ejeEstrategico: 'Desarrollo de las personas', horizonte: '2030-2040' },
  { nombre: 'Modelos fundacionales: la nueva era de la Inteligencia Artificial', tematica: 'Tecnológica', fechaActualizacion: '14 aug 2023', urlFicha: 'https://observatorio.ceplan.gob.pe/ficha/TE_16', categoria: 'Tecnología Emergente', ejeEstrategico: 'Desarrollo de las personas', horizonte: '2030-2040' },
  { nombre: 'Multimodal UI: La interacción natural entre humanos y computadoras', tematica: 'Tecnológica', fechaActualizacion: '14 aug 2023', urlFicha: 'https://observatorio.ceplan.gob.pe/ficha/TE_17', categoria: 'Tecnología Emergente', ejeEstrategico: 'Desarrollo de las personas', horizonte: '2030-2040' },
  { nombre: 'Computación neuromórfica: computadoras que imitan el cerebro humano', tematica: 'Tecnológica', fechaActualizacion: '14 aug 2023', urlFicha: 'https://observatorio.ceplan.gob.pe/ficha/TE_18', categoria: 'Tecnología Emergente', ejeEstrategico: 'Desarrollo de las personas', horizonte: '2030-2040' },
  { nombre: 'Aprendizaje auto supervisado: liberando el poder de los datos no etiquetados', tematica: 'Tecnológica', fechaActualizacion: '14 aug 2023', urlFicha: 'https://observatorio.ceplan.gob.pe/ficha/TE_19', categoria: 'Tecnología Emergente', ejeEstrategico: 'Desarrollo de las personas', horizonte: '2030-2040' },
  { nombre: 'Tokenización: transformando la seguridad y la eficiencia en las transacciones', tematica: 'Tecnológica', fechaActualizacion: '14 aug 2023', urlFicha: 'https://observatorio.ceplan.gob.pe/ficha/TE_20', categoria: 'Tecnología Emergente', ejeEstrategico: 'Desarrollo de las personas', horizonte: '2030-2040' },
  { nombre: 'Web3: La revolución de la web descentralizada', tematica: 'Tecnológica', fechaActualizacion: '14 aug 2023', urlFicha: 'https://observatorio.ceplan.gob.pe/ficha/TE_21', categoria: 'Tecnología Emergente', ejeEstrategico: 'Desarrollo de las personas', horizonte: '2030-2040' },
];